services:
  client:
    build:
      context: ./bairy-new
      dockerfile: Dockerfile
      target: builder
    container_name: client-builder
    networks:
      - app-network
    volumes:
      - client-dist:/app/dist

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      target: builder
    container_name: admin-builder
    networks:
      - app-network
    volumes:
      - admin-dist:/app/dist

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    expose:
      - 8080
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf :/etc/nginx/nginx.conf:ro
      - client-dist:/usr/share/nginx/html
      - admin-dist:/usr/share/nginx/html/admin
    depends_on:
      - client
      - admin
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  client-dist:
  admin-dist: