version: "3.9"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/uploads:/app/uploads
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-net

  nginx:
    build:
      context: ./reverse-proxy
    container_name: nginx-server
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - app-net

networks:
  app-net: