services:
  client:
    build:
      context: ./bairy-new
      dockerfile: Dockerfile
    container_name: client
    restart: always
    expose:
      - 5173
    networks:
      - app-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin
    restart: always
    expose:
      - 5174
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads: