services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    expose:
      - 8080
    volumes:
      - uploads:/app/uploads
    networks:
      - app-network

  client:
    build:
      context: ./bairy-new
      dockerfile: Dockerfile
    container_name: client
    restart: always
    expose:
      - 5173
    networks:
      - app-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin
    restart: always
    expose:
      - 5174
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - uploads:/app/uploads
    ports:
      - "80:80"
    depends_on:
      - client
      - admin
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads: